---
- name: Add the nginx signing key
  ansible.builtin.apt_key:
    id: 8540A6F18833A80E9C1653A42FD21310B49F6B46
    url: "{{ ngx_signing_key_pgp }}"
    state: present
    keyring: "{{ ngx_keyrings }}"

# installing dependent packages
- name: Installing dependencies
  ansible.builtin.apt:
    name: "{{ ngx_dependencies_packages }}"
    state: latest
    only_upgrade: true
    update_cache: true

# installing nginx packages
- name: Installing nginx packages
  ansible.builtin.apt:
    name: "{{ ngx_packages }}"
    state: present
    update_cache: true
