---

# Include variable main setup.
- name: Include variables.
  include_vars: "vars/main.yml"

# Include variables based on the distribution
- name: Include variables for {{ ansible_distribution }}
  include_vars: "vars/{{ ansible_distribution }}.yml"

- name: Define nginx_packages.
  set_fact:
    nginx_packages: "{{ __nginx_packages | list }}"
  when: nginx_packages is not defined

- name: Define nginx_install.
  set_fact:
    nginx_install: "{{ __nginx_install | bool }}"
  when: nginx_install is not defined

- name: Define nginx_sites_available_create.
  set_fact:
    nginx_sites_available_create: "{{ __nginx_sites_available_create | bool }}"
  when: nginx_sites_available_create is not defined

- name: Define nginx_sites_available_path.
  set_fact:
    nginx_sites_available_path: "{{ __nginx_sites_available_path }}"
  when: nginx_sites_available_path is not defined

- name: Define nginx_sites_enabled_create.
  set_fact:
    nginx_sites_enabled_create: "{{ __nginx_sites_enabled_create | bool }}"
  when: nginx_sites_enabled_create is not defined

- name: Define nginx_sites_enabled_path.
  set_fact:
    nginx_sites_enabled_path: "{{ __nginx_sites_enabled_path }}"
  when: nginx_sites_enabled_path is not defined

- name: Define nginx_dependent_packages.
  set_fact:
    nginx_dependent_packages: "{{ __nginx_dependent_packages }}"
  when: nginx_dependent_packages is not defined

- name: Define nginx_signing_key_pgp.
  set_fact:
    nginx_signing_key_pgp: "{{ __nginx_signing_key_pgp }}"
  when:  nginx_signing_key_pgp is not defined

- name: Define nginx_signing_key_rsa_pub.
  set_fact:
    nginx_signing_key_rsa_pub: "{{ __nginx_signing_key_rsa_pub }}"
  when: nginx_signing_key_rsa_pub is not defined

- name: Define nginx_repository.
  set_fact:
    nginx_repository: "{{ __nginx_repository }}"
  when: nginx_repository is not defined


# Include tasks based on the distribution
- name: Install nginx for {{ ansible_distribution }}
  include_tasks: "install/{{ ansible_distribution }}.yml"
  tags: install

# Create directory sites_available && sites_enabled
- name: Create directory sites_available && sites_enabled
  include_tasks: "postinstall.yml"
  tags: install

- name: Ensure NGINX is running
  meta: flush_handlers
