---

# Include variable main setup.
- name: Include variables.
  ansible.builtin.include_vars: "vars/main.yml"

# Include variables based on the distribution
- name: Include variables for {{ ansible_distribution }}
  ansible.builtin.include_vars: "vars/{{ ansible_distribution }}.yml"

- name: Define ngx_packages.
  ansible.builtin.set_fact:
    ngx_packages: "{{ __ngx_packages | list }}"
  when: nginx_packages is not defined

- name: Define ngx_sites_available_create.
  ansible.builtin.set_fact:
    ngx_sites_available_create: "{{ __ngx_sites_available_create | bool }}"
  when: ngx_sites_available_create is not defined

- name: Define ngx_sites_available_path.
  ansible.builtin.set_fact:
    ngx_sites_available_path: "{{ __ngx_sites_available_path }}"
  when: ngx_sites_available_path is not defined

- name: Define ngx_sites_enabled_create.
  ansible.builtin.set_fact:
    ngx_sites_enabled_create: "{{ __ngx_sites_enabled_create | bool }}"
  when: ngx_sites_enabled_create is not defined

- name: Define ngx_sites_enabled_path.
  ansible.builtin.set_fact:
    ngx_sites_enabled_path: "{{ __ngx_sites_enabled_path }}"
  when: ngx_sites_enabled_path is not defined

- name: Define ngx_dependencies_packages.
  ansible.builtin.set_fact:
    ngx_dependencies_packages: "{{ __ngx_dependencies_packages }}"
  when: ngx_dependencies_packages is not defined

- name: Define ngx_signing_key_pgp.
  ansible.builtin.set_fact:
    ngx_signing_key_pgp: "{{ __ngx_signing_key_pgp }}"
  when: ngx_signing_key_pgp is not defined

- name: Define ngx_signing_key_rsa_pub.
  ansible.builtin.set_fact:
    ngx_signing_key_rsa_pub: "{{ __ngx_signing_key_rsa_pub }}"
  when: ngx_signing_key_rsa_pub is not defined

- name: Define ngx_repository.
  ansible.builtin.set_fact:
    ngx_repository: "{{ __ngx_repository }}"
  when: ngx_repository is not defined

- name: Define ngx_keyrings.
  ansible.builtin.set_fact:
    ngx_keyrings: "{{ __ngx_keyrings }}"
  when: ngx_keyrings is not defined

# Include tasks based on the distribution
- name: Install nginx for {{ ansible_distribution }}
  ansible.builtin.include_tasks: "install/{{ ansible_distribution }}.yml"
  tags: install

# Create directory sites_available && sites_enabled
- name: Create directory sites_available && sites_enabled
  ansible.builtin.include_tasks: "postinstall.yml"
  tags: install

- name: Ensure NGINX is running
  ansible.builtin.meta: flush_handlers
